server {
	listen 80 default_server;
	server_name _;

	root /srv/linux-systems-site;
	index index.html;

	access_log /var/log/nginx/linux-systems.access.log;
	error_log /var/log/nginx/linux-systems.error.log warn;

	location / {
		try_files $uri $uri/ =404;
	}
}
